package GUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.ArrayList;

public class HomePanelAdmin extends JPanel {

    ToolBarPanelAdmin parentPanel;
    private List<String> reviews;

    public HomePanelAdmin(ToolBarPanelAdmin parentPanel) {
        this.parentPanel = parentPanel;
        this.reviews = new ArrayList<>();
        // Заполнение тестовыми данными
        reviews.add("Review 1 by Moderator A");
        reviews.add("Review 2 by Moderator B");
        reviews.add("Review 3 by Moderator C");

        setLayout(new GridBagLayout());
        initHomePanel();
    }

    public void initHomePanel() {
        this.setBackground(new Color(32, 38, 61));

        GridBagConstraints c = new GridBagConstraints();
        c.insets = new Insets(25, 5, 15, 10);

        // Заголовок "Home"
        JLabel home = new JLabel("Home");
        home.setFont(new Font("Dialog", Font.BOLD, 24));
        home.setForeground(Color.WHITE);
        home.setHorizontalAlignment(SwingConstants.LEFT);
        c.gridx = 0;
        c.gridy = 0;
        c.gridwidth = 3;
        c.weightx = 1.0;
        c.weighty = 0.0;
        c.fill = GridBagConstraints.HORIZONTAL;
        add(home, c);

        // Панель рецензий
        JPanel reviewApprovalPanel = createReviewApprovalPanel();
        c.gridx = 0;
        c.gridy = 1;
        c.gridwidth = 3;
        c.weightx = 1.0;
        c.weighty = 1.0;
        c.fill = GridBagConstraints.BOTH;
        add(reviewApprovalPanel, c);
    }

    private JPanel createReviewApprovalPanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        panel.setBackground(new Color(39, 47, 78));

        GridBagConstraints c = new GridBagConstraints();
        c.insets = new Insets(5, 5, 5, 5);
        c.fill = GridBagConstraints.HORIZONTAL;

        JLabel title = new JLabel("Approve Reviews");
        title.setFont(new Font("Dialog", Font.BOLD, 20));
        title.setForeground(Color.WHITE);
        c.gridx = 0;
        c.gridy = 0;
        c.gridwidth = 3;
        panel.add(title, c);

        int row = 1;
        for (String review : reviews) {
            JLabel reviewLabel = new JLabel(review);
            reviewLabel.setForeground(Color.WHITE);
            c.gridx = 0;
            c.gridy = row;
            c.gridwidth = 2;
            panel.add(reviewLabel, c);

            JButton approveButton = new JButton("Approve");
            approveButton.addActionListener(e -> approveReview(review));
            c.gridx = 2;
            c.gridy = row;
            c.gridwidth = 1;
            panel.add(approveButton, c);

            row++;
        }

        return panel;
    }

    private void approveReview(String review) {
        // Логика одобрения рецензии
        reviews.remove(review);
        JOptionPane.showMessageDialog(this, "Review approved: " + review);
        // Обновление панели
        removeAll();
        initHomePanel();
        revalidate();
        repaint();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
    }
}
