package View.Admin;

import javax.swing.*;
import java.awt.*;

public class AdminFrame extends JFrame {

    private String admin;

    public JPanel mainPanel;
    public JPanel contentPanel;
    public JScrollPane scrollPane;

    public AdminFrame(String userName) {
        admin = userName;
        adminUI();
    }

    public void adminUI() {
        setTitle("Genius App");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(1440, 1024);
        getContentPane().setBackground(new Color(32, 38, 61));
        initAdminFrame();
        setVisible(true);
    }

    public void initAdminFrame() {
        mainPanel = new JPanel();
        mainPanel.setBackground(new Color(32, 38, 61));
        mainPanel.setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();

        ToolBarPanelAdmin toolBarPanel = new ToolBarPanelAdmin(this);
        toolBarPanel.setBackground(new Color(39, 47, 78));

        c.gridx = 0;
        c.gridy = 0;
        c.gridwidth = 1;
        c.gridheight = 1;
        c.fill = GridBagConstraints.BOTH;
        c.weightx = 0.15;
        c.weighty = 1;
        c.insets = new Insets(0, 166, 0, 0);
        mainPanel.add(toolBarPanel, c);

        contentPanel = new HomePanelAdmin(toolBarPanel);
        contentPanel.setBackground(new Color(32, 38, 61));
        c.gridx = 1;
        c.gridy = 0;
        c.gridwidth = 1;
        c.gridheight = 1;
        c.fill = GridBagConstraints.BOTH;
        c.weightx = 0.85;
        c.weighty = 1;
        c.insets = new Insets(0, 0, 0, 0);

        scrollPane = new JScrollPane(contentPanel);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        mainPanel.add(scrollPane, c);

        this.add(mainPanel);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
    }
}
