package View.Admin;

import Enums.TypeOfArtist;
import Models.Artist;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ArtistFormPanel extends JPanel {

    private JTextField idField;
    private DefaultListModel<String> listModel;

    public ArtistFormPanel() {
        setLayout(new GridBagLayout());
        initFormPanel();
    }

    private void initFormPanel() {
        GridBagConstraints c = new GridBagConstraints();
        c.insets = new Insets(5, 5, 5, 5);

        JLabel idLabel = new JLabel("Artist ID:");
        c.gridx = 0;
        c.gridy = 0;
        add(idLabel, c);

        idField = new JTextField(20);
        c.gridx = 1;
        c.gridy = 0;
        add(idField, c);

        JButton addButton = new JButton("Add Artist");
        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addArtist();
            }
        });
        c.gridx = 0;
        c.gridy = 1;
        c.gridwidth = 2;
        add(addButton, c);

        listModel = new DefaultListModel<>();
        JList<String> artistList = new JList<>(listModel);
        artistList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        JScrollPane listScrollPane = new JScrollPane(artistList);
        c.gridx = 0;
        c.gridy = 2;
        c.gridwidth = 2;
        c.weightx = 1.0;
        c.weighty = 1.0;
        c.fill = GridBagConstraints.BOTH;
        add(listScrollPane, c);
    }

    private void addArtist() {
        String id = idField.getText();
        if (!id.isEmpty()) {
            Artist artist = new Artist(id, null, TypeOfArtist.SINGLE_ARTIST) {
            };
            listModel.addElement(artist.getId());
            idField.setText("");
        }
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Artist Management");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 300);
        frame.add(new ArtistFormPanel());
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
    }
}
