package View.Admin;

import Models.Bend;
import Models.RecordLabel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;

public class BandFormPanel extends JPanel {

    private JTextField idField;
    private JTextField nameField;
    private JTextField descriptionField;
    private JTextField dateField;
    private DefaultListModel<String> listModel;

    public BandFormPanel() {
        setLayout(new GridBagLayout());
        initFormPanel();
    }

    private void initFormPanel() {
        GridBagConstraints c = new GridBagConstraints();
        c.insets = new Insets(5, 5, 5, 5);

        JLabel idLabel = new JLabel("Band ID:");
        c.gridx = 0;
        c.gridy = 0;
        add(idLabel, c);

        idField = new JTextField(20);
        c.gridx = 1;
        c.gridy = 0;
        add(idField, c);

        JLabel nameLabel = new JLabel("Name:");
        c.gridx = 0;
        c.gridy = 1;
        add(nameLabel, c);

        nameField = new JTextField(20);
        c.gridx = 1;
        c.gridy = 1;
        add(nameField, c);

        JLabel descriptionLabel = new JLabel("Description:");
        c.gridx = 0;
        c.gridy = 2;
        add(descriptionLabel, c);

        descriptionField = new JTextField(20);
        c.gridx = 1;
        c.gridy = 2;
        add(descriptionField, c);

        JLabel dateLabel = new JLabel("Date of Establishment:");
        c.gridx = 0;
        c.gridy = 3;
        add(dateLabel, c);

        dateField = new JTextField(20);
        c.gridx = 1;
        c.gridy = 3;
        add(dateField, c);

        JButton addButton = new JButton("Add Band");
        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addBand();
            }
        });
        c.gridx = 0;
        c.gridy = 4;
        c.gridwidth = 2;
        add(addButton, c);

        listModel = new DefaultListModel<>();
        JList<String> bandList = new JList<>(listModel);
        bandList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        JScrollPane listScrollPane = new JScrollPane(bandList);
        c.gridx = 0;
        c.gridy = 5;
        c.gridwidth = 2;
        c.weightx = 1.0;
        c.weighty = 1.0;
        c.fill = GridBagConstraints.BOTH;
        add(listScrollPane, c);
    }

    private void addBand() {
        String id = idField.getText();
        String name = nameField.getText();
        String description = descriptionField.getText();
        LocalDate dateOfEstablishment = LocalDate.parse(dateField.getText());

        if (!id.isEmpty() && !name.isEmpty() && !description.isEmpty() && dateOfEstablishment != null) {
            Bend band = new Bend(id, null, name, description, dateOfEstablishment);
            listModel.addElement(band.getId() + ", " + band.getName());
            idField.setText("");
            nameField.setText("");
            descriptionField.setText("");
            dateField.setText("");
        }
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Band Management");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 300);
        frame.add(new BandFormPanel());
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
    }
}
